server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  main:
    allow-circular-references: true

  mvc:
    view:
      prefix: /templates/jsp/
      suffix: .jsp


  profiles:
    include: oauth

  mariadb:
    console:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://localhost:3306/member

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 309433611452-5sce3smen7dt0dpvahldhsl3vmdj6p88.apps.googleusercontent.com
            client-secret: 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
            scope:
               - email
               - profile

          facebook:
            client-id: 441770567871108
            client-secret: f1d59c64a9685da682fd5d9fdc677d98
            scope:
              - email
              - public_profile

          naver:
            client-id: n7j6r1lteJCJ1wetkyIg
            client-secret: dJS8SySRXf
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
